spring:
  application:
    name: clienteEurekaMSPersonas
server:
  port: 9001
eureka:
  client:
    register-with-eureka: false    
    serviceUrl:      
      defaultZone: http://192.168.1.41:8761/eureka